### ISSUE TITLE
How to use rbd-wnbd to fix the drive letter on windows10?

### ISSUE THREAD

**Issue by luckyho** [cloudbase/wnbd#135]
I formatted the rbd image and installed the system image and specified the drive letter T. Then I cloned the rbd image and mapping the cloned image to other windows machines. The drive letter of the cloned image is Automatically assigned, such as drive letter E.

In this scenario, how can I ensure that the drive letter of this cloned image is T after mapping?

**Comment by petrutlucian94** [comment]
Hi,

Windows drive letters are not preserved when the disks are reattached to other hosts. Here are a few alternatives:

1. Use volume GUID paths such as ``\\?\Volume{b3fcaf41-c404-4942-9720-4e60d62217e1}\``. The GUID will be preserved, however not all Windows applications can handle such paths.

2. Identify the drive letter based on the volume id or filesystem label:
```
PS C:\> get-volume | ? { $_.UniqueId -eq '\\?\Volume{b3fcaf41-c404-4942-9720-4e60d62217e1}\' }

DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining
----------- ------------ -------------- --------- ------------ ----------------- -------------
T           test1g       NTFS           Fixed     Healthy      OK                    993.12 MB


PS C:\> get-volume | ? { $_.FileSystemLabel -eq "test1g" }

DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining
----------- ------------ -------------- --------- ------------ ----------------- -------------
T           test1g       NTFS           Fixed     Healthy      OK                    993.12 MB
```
3. Probably the best option: use volume mount points (access points) instead of relying on drive letters:

```
PS C:\> mkdir C:\mnt\test_1g\ -force
PS C:\> Get-Partition -DriveLetter t | Add-PartitionAccessPath -AccessPath C:\mnt\test_1g\
```

I'll go ahead and close this issue since it concerns Windows partition access points and not WNBD in particular. Let me know if you have any further questions though.
