### ISSUE TITLE
Build doesn't work if build path has spaces in it

### ISSUE THREAD

**Issue by yoe** [cloudbase/wnbd#27]
Finally tried to make some time to give this an in-depth review. When I try to build this on my Windows VM, I get:

```
PreBuildEvent:
  powershell.exe -executionpolicy bypass C:\Users\Wouter Verhelst\source\repos\wnbd\vstudio\generate_version_h.ps1
  :VCEnd
  C:\Users\Wouter : The term 'C:\Users\Wouter' is not recognized as the name of a cmdlet, function, script file, or ope
  ra
  ble program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
  .
  At line:1 char:1
  + C:\Users\Wouter Verhelst\source\repos\wnbd\vstudio\generate_version_h ...
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (C:\Users\Wouter:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
```

Things are obviously very unhappy after that.

**Comment by petrutlucian94** [comment]
Thanks for giving it a try!

Looks like that path should've been quoted, otherwise it will error out if it contains whitespaces. Can you please use a path that doesn't contain whitespaces for now? We'll fix the Visual Studio solution as soon as possible.

As an alternative, you can fetch prebuilt binaries from here, the appveyor artifacts:
https://ci.appveyor.com/api/buildjobs/x7ulpc8at5hqicio/artifacts/wnbd-Release.zip
https://ci.appveyor.com/project/aserdean/wnbd/branch/master

**Comment by yoe** [comment]
Yeah, I did copy it to `C:\wnbd` and that did get me a bit further, but I thought I'd report bugs as I find them ;-)

(I do get stuck a bit further down the build, not sure yet whether it's me being stupid or whether that's another bug. In the latter case, you'll see another bug report appear soon, I promise! ;-) )

**Comment by petrutlucian94** [comment]
That's great, please do report any issue or suggestion that you might have.

Feel free to ping me on freenode as well, my IRC handle is lpetrut. I might be able to assist you.
